/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#ffdcbc', 'on-tertiary-fixed': '#171e10',
        'surface-bright': '#fff8f1', 'surface-container-high': '#efe7dd',
        'tertiary-container': '#6f7765', 'on-primary': '#ffffff',
        'on-primary-fixed': '#171d10', 'inverse-surface': '#33302a',
        surface: '#fff8f1', 'secondary-container': '#fecb97', 'on-error': '#ffffff',
        'on-background': '#1e1b15', 'error-container': '#ffdad6', 'surface-tint': '#5a614f',
        primary: '#585e4d', 'primary-fixed': '#dee5cf', tertiary: '#575f4e',
        'on-tertiary-fixed-variant': '#414939', 'surface-container-lowest': '#ffffff',
        'primary-container': '#707765', 'secondary-fixed-dim': '#efbd8a', secondary: '#7c572d',
        'primary-fixed-dim': '#c2c9b4', 'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#c1c9b5', 'surface-container': '#f4ede3',
        'on-surface-variant': '#454840', 'surface-dim': '#e0d9cf', 'inverse-primary': '#c2c9b4',
        background: '#fff8f1', 'on-primary-fixed-variant': '#424939', 'on-tertiary': '#ffffff',
        'tertiary-fixed': '#dde6d0', outline: '#767870', 'on-error-container': '#93000a',
        'on-secondary-fixed': '#2c1700', 'on-secondary-fixed-variant': '#614018',
        'surface-variant': '#e9e1d8', 'on-primary-container': '#f9ffea',
        'on-tertiary-container': '#f9ffec', error: '#ba1a1a',
        'surface-container-low': '#faf2e9', 'inverse-on-surface': '#f7f0e6',
        'on-secondary-container': '#79542a', 'surface-container-highest': '#e9e1d8',
        'outline-variant': '#c6c7be', 'on-surface': '#1e1b15',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      spacing: {
        'space-2xs': '0.25rem', 'space-xs': '0.5rem', 'space-sm': '0.75rem',
        'space-md': '1rem', 'space-lg': '1.5rem', 'space-xl': '2rem',
        'space-2xl': '3rem', 'space-3xl': '4.5rem', 'space-mobile': '1rem',
        'margin-mobile': '1.25rem', 'gutter-tablet': '1.5rem', 'margin-tablet': '2rem',
        'gutter-desktop': '2rem', 'margin-desktop': '3rem', 'content-max-width': '84rem',
      },
      fontFamily: { manrope: ['Manrope', 'sans-serif'] },
      fontSize: {
        'body-lg': ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '0em', fontWeight: '400' }],
        display: ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-lg': ['1.125rem', { lineHeight: '1.625rem', letterSpacing: '-0.005em', fontWeight: '600' }],
        'metric-display': ['2.5rem', { lineHeight: '3rem', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.25rem', letterSpacing: '0.005em', fontWeight: '400' }],
        'headline-lg-mobile': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-md': ['0.9375rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '400' }],
        'display-mobile': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md-mobile': ['1.375rem', { lineHeight: '1.875rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.025em', fontWeight: '600' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '600' }],
        'title-md': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '500' }],
        'headline-md': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.015em', fontWeight: '600' }],
      },
    },
  },
}
